apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mono789/rest-kubernetes'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true